config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :users, only: [:index, :show]

  namespace :dashboard do
    resources :api, only: :index
    resources :users do
      member do
        get :edit_password
        post :update_password
      end
    end
    resources :tasks do
      member do
        post :assign_to_me
      end
      resources :attachments, only: :destroy
    end
  end

  root 'welcome#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  mount_uploader :file, FileUploader

  before_create do
    self.original_file = self.file.original_file
  end
end

app/models/concerns/state_machine.rb
module StateMachine
  extend ActiveSupport::Concern

  included do
    enum state: { fresh: 0, started: 1, finished: 2 }
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include StateMachine

  validates :name, :description, presence: true

  has_many :attachments
  belongs_to :user

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  def assign_to(user)
    update(user_id: user.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  include StateMachine
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tasks, dependent: :destroy

  before_create :generate_api_token

  def update_password!(current_password, new_password, confirm_password)
    unless valid_password?(current_password)
      errors.add(:current_password, "не верный.")
      return false
    end

    reset_password(new_password, confirm_password)
  end

  private

  def generate_api_token
    self.token = SecureRandom.hex(32)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard/api_controller.rb
class Dashboard::ApiController < Dashboard::DashboardController
  def index
  end
end

app/controllers/dashboard/attachments_controller.rb
class Dashboard::AttachmentsController < Dashboard::DashboardController
  def destroy
    Task.find(params[:task_id]).attachments.find(params[:id]).destroy
    redirect_to dashboard_task_path(params[:task_id])
  end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ActionController::Base
  protect_from_forgery with: :exception, unless: -> { request.format.json? }


  before_action :auth_by_token
  before_action :authenticate_user!

  layout 'dashboard'


  private

  def auth_by_token
    if request.format.json?
      user = User.find_by_token(params[:token])
      if user
        sign_in(:user, user)
      else
        render nothing: true, status: 401
      end
    end
  end

end

app/controllers/dashboard/tasks_controller.rb
class Dashboard::TasksController < Dashboard::DashboardController


  def index
    @tasks = current_user.tasks

    respond_to do |format|
      format.html do
        @tasks = @tasks.page(params[:page]).per(10)
      end
      format.json { render layout: false }
    end
  end

  def assign_to_me
    @task = Task.find(params[:id])
    @task.assign_to(current_user)

    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.json { render layout: false }
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      respond_to do |format|
        format.html do
          redirect_to dashboard_task_path(@task)
        end
        format.json { render layout: false }
      end
    else
      respond_to do |format|
        format.html do
          render action: :edit
        end
        format.json { render layout: false }
      end
    end
  end

  def show
    @task = Task.find(params[:id])
    respond_to do |format|
      format.html
      # FIXME
      # Looks like a bug, if I use:
      # format.json { render layout: false }
      # rails still render show.slim, but we have show.jbuilder... Need more time for resolve that..
      format.json { render json: {task: @task}.to_json}
    end
  end

  def new
    @task = Task.new
    @task.attachments.build
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      respond_to do |format|
        format.html do
          redirect_to dashboard_task_path(@task)
        end
        format.json { render layout: false }
      end
    else
      respond_to do |format|
        format.html do
          render action: :new
        end
        format.json { render layout: false }
      end
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :state, :user_id, attachments_attributes: [:id, :file, :_destroy])
  end

  private

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::DashboardController
  before_action :init_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_user_path(@user)
    else
      render action: :edit
    end
  end

  def edit_password
  end

  def update_password
    if @user.update_password!(params[:user][:current_password], params[:user][:password], params[:user][:password_confirmation])
      redirect_to root_path
    else
      render action: :edit_password
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end

  def init_user
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tasks = Task.order('created_at desc').page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/api_helper.rb
module Dashboard::ApiHelper
end

app/helpers/dashboard/attachments_helper.rb
module Dashboard::AttachmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_header(user)
    if current_user == user
      'Мой профиль'
    else
      "Профиль #{current_user.email}"
    end
  end
end

app/views/dashboard/api/index.slim
h1
  | API

p
  | Для авторизации запроса, используйте token=
  = current_user.token
p
  | Обратите внимание, что если вы делаете запрос на создание объекта, ответ будет содержать ваш объект с дополнительным атрибутом errors. Именно по нему вы должны ориентироваться, произошла ли ошибка создания или нет. Если да, errors покажет вам ошибку для кажного поля.

h2 List
table.table
  thead
    tr
      th
        | Метод
      th
        | URL
  tbody
    tr
      td
        | GET
      td
        | /dashboard/tasks.json?token=my_token

h2 Show
table.table
  thead
    tr
      th
        | Метод
      th
        | URL
  tbody
    tr
      td
        | GET
      td
        | /dashboard/tasks/:id.json?token=my_token

h2 Create
table.table
  thead
    tr
      th
        | Метод
      th
        | URL
  tbody
    tr
      td
        | POST
      td
        | /dashboard/tasks.json?token=my_token
    tr
      td{colspan=2}
        | task: { name: 'name', description: 'description', state: 'state', user_id: 1 }

h2 Update
table.table
  thead
    tr
      th
        | Метод
      th
        | URL
  tbody
    tr
      td
        | PUT
      td
        | /dashboard/tasks/:id.json?token=my_token
    tr
      td{colspan=2}
        | task: { name: 'name', description: 'description', state: 'state', user_id: 1 }

h2 Assign to me
table.table
  thead
    tr
      th
        | Метод
      th
        | URL
  tbody
    tr
      td
        | POST
      td
        | /dashboard/tasks/:id/assign_to_me?token=my_token

app/views/dashboard/tasks/_attachment_fields.slim
.nested-fields
  .field
    = f.file_field :file
    = f.object.original_file
  = link_to_remove_association 'Удалить фаил', f

app/views/dashboard/tasks/_form.slim
= form_for [:dashboard, @task] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  p.text-danger
    = @task.errors.full_messages_for(:name).join(', ')
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  p.text-danger
    = @task.errors.full_messages_for(:description).join(', ')
  .form-group
    = f.label :state
    = select_tag "task[state]", options_for_select(Task.states.keys, @task.state), class: 'form-control'
  .form-group
    = f.label :user
    = f.select :user_id, options_from_collection_for_select(User.all, 'id', 'email', @task.user ? @task.user.id : nil), {include_blank: true}, class: 'form-control'
  p.text-danger
    = @task.errors.full_messages_for(:user).join(', ')
  h3 Files
  #tasks
    = f.fields_for :attachments do |file_form|
      = render 'attachment_fields', f: file_form
    .links
      = link_to_add_association 'Добавить фаил', f, :attachments
  br

  = f.submit @task.new_record? ? 'Сохранить' : 'Обновить', class: 'btn btn-primary'

app/views/dashboard/tasks/edit.slim
- content_for :seo_title
  - 'Редактирование тикета'

h1
  | Редактирование тикета

= render partial: 'form'

app/views/dashboard/tasks/index.html.slim
- content_for :seo_title
  - 'Список моих задач'

H1
  | Список моих задач

= render partial: 'shared/list_tasks'

= paginate @tasks, :theme => 'twitter-bootstrap-3'

app/views/dashboard/tasks/new.slim
- content_for :seo_title
  - 'Создание нового тикета'

h1
  | Создание нового тикета

= render partial: 'form'

app/views/dashboard/tasks/show.slim
h1
  | Тикет

label
  ' Название:
p
  = @task.name
label
  ' Описание:
p
  = @task.description
label
  ' Статус
p
  = @task.state

- if @task.user
  label
    ' Назначина:
  p
    = @task.user.email
- if @task.attachments.present?
  table.table.table-striped
    thead
      tr
        th
          | Имя файла
        th
          | Действие
        th
          | Размер
    - @task.attachments.each do |attach|
      tr
        td
          = link_to attach.original_file, attach.file.url
        td
          = link_to 'Удалить', dashboard_task_attachment_path(task_id: @task, id: attach.id), method: :delete, data: {confirm: 'Вы уверенны?'}, class: 'btn btn-xs btn-primary'
        td
          = attach.file_size


= link_to 'Редаткировать', edit_dashboard_task_path(@task)

app/views/dashboard/users/edit.slim
- content_for :seo_title
  - 'Редактирование профайла'

h1
  | Редактирование профайла

= form_for [:dashboard, @user] do |f|
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
  p.text-danger
    = @user.errors.full_messages_for(:email).join(', ')
  = f.submit "Обновить", class: 'btn btn-primary'

app/views/dashboard/users/edit_password.slim
.row
  .col-sm-3.hidden-xs
  .col-md-6
    h1
      | Смена пароля

    = form_for [:dashboard, @user], url: update_password_dashboard_user_path(@user), method: :post do |f|
      .form-group class="#{'has-error' if @user.errors.full_messages_for(:current_password).present?}"
        = label_tag 'Текущий пароль'
        = f.password_field :current_password, class: 'form-control'
        p.text-danger
          = @user.errors.full_messages_for(:current_password).join(', ')

        = label_tag 'Новый пароль'
        = f.password_field :password, class: 'form-control'
        p.text-danger
          = @user.errors.full_messages_for(:password).join(', ')

        = label_tag 'Повторите новый пароль'
        = f.password_field :password_confirmation, class: 'form-control'
        p.text-danger
          = @user.errors.full_messages_for(:password_confirmation).join(', ')

      = f.submit 'Сохранить', class: 'btn btn-primary'

  .col-sm-3.hidden-xs

app/views/dashboard/users/show.slim
= render partial: 'shared/profile'

- if current_user == @user
  = link_to 'Редактировать профаил', edit_dashboard_user_path(current_user)
  br
  = link_to 'Сменить пароль', edit_password_dashboard_user_path(current_user)

app/views/layouts/application.slim
doctype html
html
  head
    title
      = yield :seo_title
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Task manager
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"  Task manager
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li{class="#{'active' if controller_name == 'welcome'}"}
              = link_to 'Список задач', root_path
            - if current_user
              li{class="#{'active' if controller_name == 'users' && current_user.id != params[:id].to_i}"}
                = link_to 'Пользователи', users_path
          ul.nav.navbar-nav.navbar-right
            - if current_user
              li{class="#{'active' if controller_name == 'users' && current_user.id == params[:id].to_i}"}
                = link_to 'Профиль', user_path(current_user)
              li
                = link_to 'Выйти', destroy_user_session_path, method: :delete
            - else
              li
                = link_to 'Регистрация', new_user_registration_path
              li
                = link_to 'Авторизация', new_user_session_path

    .container
      .col-sm-3.hidden-xs
      .col-md-6
        = yield
      .col-md-3.hidden-xs

app/views/layouts/dashboard.slim
doctype html
html
  head
    title
      = yield :seo_title
    = stylesheet_link_tag 'dashboard/application', media: 'all'
    = javascript_include_tag 'dashboard/application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Dashboard
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'DASHBOARD', dashboard_user_path(current_user), class: 'navbar-brand'
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li{class="#{'active' if controller_name == 'tasks'}"}
              = link_to 'Мои задачи', dashboard_tasks_path
            li{class="#{'active' if controller_name == 'users'}"}
              = link_to 'Профиль', dashboard_user_path(current_user)
            li{class="#{'active' if controller_name == 'api'}"}
              = link_to 'API', dashboard_api_index_path

          ul.nav.navbar-nav.navbar-right
            - if current_user
              li
                = link_to 'Главная страница', root_path
              li
                = link_to 'Выйти', destroy_user_session_path, method: :delete
            - else
              li
                = link_to 'Регистрация', new_user_registration_path
              li
                = link_to 'Авторизация', new_user_session_path

    .container
      .col-xs-1.hidden-xs
      .col-xs-10
        = yield
      .col-xs-1.hidden-xs

app/views/shared/_list_tasks.slim
- if current_user
  .row
    .col-xs-12.text-right
      = link_to 'Новая задача', new_dashboard_task_path, class: 'btn btn-primary'

- @tasks.each do |task|
  .row.task
    .col-xs-12
      .row
        .col-xs-12
          h2
            = task.name
      .row
        .col-xs-12
          = task.description
      .row
        .col-xs-12
          b
            - if task.user
              ' Назначенна:
              = link_to task.user.email, user_path(task.user.id)
            - else
              | Не назначенна
      .row
        .col-xs-4
          b
            = I18n.l(task.created_at, format: :long)
        .col-xs-8
          b
            = task.state
      .row
        .col-xs-12.text-right
          - if current_user && task.user.nil?
            = link_to 'Назначить на себя', assign_to_me_dashboard_task_path(task), class: 'btn btn-xs btn-info', method: :post
          - if current_user
            = link_to 'Редактировать', edit_dashboard_task_path(task), class: "btn btn-xs btn-default"
            = link_to 'Показать', dashboard_task_path(task), class: "btn btn-xs btn-default"

app/views/shared/_profile.slim
- content_for :seo_title
  | Профаил пользователя

h1
  ' Профаил пользователя

p
  | Email:
  = @user.email
p
  ' Число назначенных тасков:
  = @user.tasks.count

app/views/tasks/_form.slim
= form_for @task do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  p.text-danger
    = @task.errors.full_messages_for(:name).join(', ')
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  p.text-danger
    = @task.errors.full_messages_for(:description).join(', ')
  .form-group
    = f.label :state
    = select_tag "task[state]", options_for_select(Task.states.keys, @task.state), class: 'form-control'
  .form-group
    = f.label :user
    = f.select :user_id, options_from_collection_for_select(User.all, 'id', 'email', @task.user ? @task.user.id : nil), {include_blank: true}, class: 'form-control'
  p.text-danger
    = @task.errors.full_messages_for(:user).join(', ')
  = f.submit @task.new_record? ? 'Сохранить' : 'Обновить', class: 'btn btn-primary'

app/views/tasks/show.slim
h1
  | Тикет

label
  ' Название:
p
  = @task.name
label
  ' Описание:
p
  = @task.description
label
  ' Статус
p
  = @task.state

- if @task.user
  label
    ' Назначина:
  p
    = @task.user.email

= link_to 'Редаткировать', edit_task_path(@task)

app/views/users/edit.slim
- content_for :seo_title
  - 'Редактирование профайла'

h1
  | Редактирование профайла

= form_for @user do |f|
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
  p.text-danger
    = @user.errors.full_messages_for(:email).join(', ')
  = f.submit "Обновить", class: 'btn btn-primary'

app/views/users/edit_password.slim
.row
  .col-sm-3.hidden-xs
  .col-md-6
    h1
      | Смена пароля

    = form_for @user, url: update_password_user_path(@user), method: :post do |f|
      .form-group class="#{'has-error' if @user.errors.full_messages_for(:current_password).present?}"
        = label_tag 'Текущий пароль'
        = f.password_field :current_password, class: 'form-control'
        p.text-danger
          = @user.errors.full_messages_for(:current_password).join(', ')

        = label_tag 'Новый пароль'
        = f.password_field :password, class: 'form-control'
        p.text-danger
          = @user.errors.full_messages_for(:password).join(', ')

        = label_tag 'Повторите новый пароль'
        = f.password_field :password_confirmation, class: 'form-control'
        p.text-danger
          = @user.errors.full_messages_for(:password_confirmation).join(', ')

      = f.submit 'Сохранить', class: 'btn btn-primary'

  .col-sm-3.hidden-xs

app/views/users/index.slim
h1
  | Пользователи на проекте

- @users.each do |user|
  p
    = link_to user.email, user_path(user)

app/views/users/show.slim
= render partial: 'shared/profile'

app/views/welcome/index.html.slim
- content_for :seo_title
  - 'Список задач'

H1
  | Список задач
= render partial: 'shared/list_tasks'

= paginate @tasks, :theme => 'twitter-bootstrap-3'